name: Deploy Ahoy
on:
  release:
    types:
      - released
  push:
    branches: [ main ]
concurrency: deployment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: pdo_mysql
          coverage: none
          tools: composer:v2
      - run: composer install
      - name: Add identity file
        run: echo "${{ secrets.PRIVATE_KEY }}" >> $HOME/deploy.key
        env:
          SSH_PRIVATE_KEY: ${{secrets.PLATFORMSH_PRIVATE_KEY}}
      - name: Keyscan
        run: ssh-keyscan 142.93.193.17 >> $HOME/.ssh/known_hosts
      - run: rsync -e "ssh -i $HOME/deploy.key" -rzcEl . root@142.93.193.17:/var/www/html --exclude-from=".rsyncignore" --checksum --delete
